# Header

menu:
  主页: /
  所有文章: /archives
  留言: /message

# SubNav
subnav:
  github: "https://github.com/haloMelody"
  weibo: "https://weibo.com/HaloMelody"
  #rss: "#"
  zhihu: "https://www.zhihu.com/people/tang-long-48-86/activities"
  #qq: "https://user.qzone.qq.com/996830452"
  #weixin: "#"
  jianshu: "http://www.jianshu.com/users/9f63ab292460/timeline"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。

# Content
# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: 老板大气，谢谢老板！
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: http://ou36vgj5u.bkt.clouddn.com/image/blog/alipay.JPG
# 微信二维码图片地址
weixin: http://ou36vgj5u.bkt.clouddn.com/image/blog/wechatpay.JPG

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: '24451a8b853bb443019686be21dfdff4'
google_analytics: ''
favicon: http://ou36vgj5u.bkt.clouddn.com/image/blog/fav.ico

#你的头像url
avatar: http://ou36vgj5u.bkt.clouddn.com/image/blog/head.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#2、来必力
livere: true
livere_uid: 'MTAyMC8zMDA1MC82NjE0'

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false
disqus_shortname: halomelody

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '文章查找'
  friends: '友链'
  aboutme: '关于我'
  #tagcloud: '标签'

friends:
  李总: https://catalinaLi.github.io
  石总: https://minigoooo.github.io
  小红: http://weibo.com/heiRed

aboutme: 生活不止眼前的苟且，还有诗和远方的田野</br>没有故事，酒也喝不起

# 页面统计 true为开启
page_count: true

# 站点访问次数统计 true为开启
site_count: true

# 站点访问人数数统计 true为开启
user_count: true